AllCops:
  NewCops: enable # 新しい設定を導入する
  # 自動生成されるファイルを除外
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Style/RegexpLiteral:
  EnforcedStyle: percent_r
