version: 2.1

jobs:
  build:
    working_directory: ~/booster
    docker:
      - image: cimg/ruby:3.0.2-node
        environment:
          RAILS_ENV: test
          BUNDLE_PATH: vendor/bundle
      - image: circleci/mysql:5.7
        name: db
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: booster_test
    steps:
      - checkout
      - restore_cache:
          key: z1 -dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Bundler install
          command: gem install bundler
      - run:
          name: Bundle Install Dependencies
          command: |
            bundle config set --local path 'vendor/bundle'
            bundle install
      - save_cache:
          key: z1 -dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  test:
    working_directory: ~/booster
    docker:
      - image: cimg/ruby:3.0.2-node
        environment:
          RAILS_ENV: test
          DATABASE_HOST: 127.0.0.1 
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: booster_test
    steps:
      - checkout
      # MySQLと接続できるまで待ちます
      - run:
          name: "waiting DB start"
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
      - restore_cache:
          key: z1 -dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Bundler install
          command: gem install bundler
      - run:
          name: Bundle Install Dependencies
          command: |
            bundle config set --local path 'vendor/bundle'
            bundle install
      - save_cache:
          key: z1 -dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: "initialize DB"
          command: |
            bundle exec rails db:create
            bundle exec rails db:migrate
      - run:
          name: RSpec
          command: bundle exec rspec

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
