version: 2

jobs:
  test:
    docker:
      - image: circleci/ruby:3.0.2-node
        environment:
          RAILS_ENV: test
          DATABASE_HOST: 127.0.0.1 
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: booster_test
    working_directory: ~/booster
    steps:
      - checkout
      - run:
          name: "bundle install"
          command: bundle install
      # MySQLと接続できるまで待ちます
      - run:
          name: "waiting DB start"
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
      - run:
          name: "initialize DB"
          command: |
            bundle exec rails db:create
            bundle exec rails db:migrate
      - run:
          name: RSpec
          command: bundle exec rspec

workflows:
  version: 2
  workflows:
    jobs:
      - test
